---
stages:
  - test

before_script:
  - export http_proxy=http://wwwproxy.sandia.gov:80
  - export https_proxy=http://wwwproxy.sandia.gov:80
  - export no_proxy=*.sandia.gov
  - docker info

 build_image:
   script:
     - docker-compose -f docker-compose-custom.yml build