language: perl
cache:
  - apt
perl:
  - "5.18"
install: "sudo ./ubuntu_installer.sh -m test"
script: "cd /opt/sandia/webapps/scot3/t/ && perl /opt/sandia/webapps/scot3/t/all.t"
after_success: $DEPLOY
