language: generic
services:
  - docker
  
install:
  - docker-compose -f docker-compose-custom.yml build
  
deploy:
  provider: script
  script: bash script/docker-build-push
  on:
    branch: master
