version: '3'
services:
  apache:
    build:
      dockerfile: Dockerfile-Apache
      context: ./
    volumes: 
     - "/etc/timezone:/etc/timezone:ro"
     - "/etc/localtime:/etc/localtime:ro"
     - "/var/log/apache2:/var/log/apache2/"
    ports:
     - "443:443"
     - "80:80"
    networks:
     - scot-docker-net
  activemq:
    volumes:
     - "/var/log/activemq:/var/log/activemq/log/"
    build:
      dockerfile: Dockerfile-Activemq
      context: ./
    #image: https://baltig.sandia.gov:4567/scot-activemq
    ports:
     - "8161:8161"
     - "61613:61613"
    networks:
     - scot-docker-net
  
  mongodb:
    build:
      dockerfile: Dockerfile-Mongodb
      context: ./
    volumes:
     - "/var/log/mongodb/mongod.log:/var/log/mongodb/mongod.log"
     - "/etc/timezone:/etc/timezone:ro"
     - "/etc/localtime:/etc/localtime:ro"
     - "/var/lib/mongodb:/var/lib/mongodb/"
    networks:
     - scot-docker-net
    ports:
     - "27017:27017"
  
  elastic:
   build:
     dockerfile: Dockerfile-Elastic
     context: ./
   volumes:
     - "/etc/timezone:/etc/timezone:ro"
     - "/etc/localtime:/etc/localtime:ro"
     - "/opt/scotbackup/elastic:/opt/scotbackup/elastic/"
   networks:
    - scot-docker-net
   ports:
    - "9200:9200"

  mapping:
    build:
      dockerfile: Dockerfile-Mapping
      context: ./
    depends_on:
     - elastic
    networks:
     - scot-docker-net

  scot:
    build:
      dockerfile: Dockerfile-Scot
      context: ./
    volumes:
     - "/var/log/scot:/var/log/scot/"
     - "/etc/timezone:/etc/timezone:ro"
     - "/etc/localtime:/etc/localtime:ro"
     - "/opt/scotfiles:/opt/scotfiles/"
     - "/opt/scot/public/cached_images:/opt/scot/public/cached_images/"
    depends_on:
     - perl
     - mapping
     - mongodb
     - activemq
    networks:
     - scot-docker-net
    ports:
     - "3000:3000"
  perl:
    build: 
      dockerfile: Dockerfile-Perl
      context: ./
    image: scot_perl


  flair:
   build:
     dockerfile: Dockerfile-Flair
     context: ./
   volumes:
    - "/var/log/scot:/var/log/scot/"
   depends_on:
    - mongodb
    - activemq
    - scot
   networks:
     - scot-docker-net

  stretch:
   build:
     dockerfile: Dockerfile-Stretch
     context: ./
   volumes:
    - "/var/log/scot:/var/log/scot/"
   depends_on:
    - mongodb
    - activemq
    - scot
   networks:
    - scot-docker-net
  
  game:
   build:
     dockerfile: Dockerfile-Game
     context: ./
   volumes:
    - "/var/log/scot:/var/log/scot/"
   depends_on:
    - mongodb
    - scot
   networks:
     - scot-docker-net

networks:
  scot-docker-net:
    driver: bridge
