version: '3.4'
services:
  apache:
    volumes: 
     - "/etc/timezone:/etc/timezone:ro"
     - "/etc/localtime:/etc/localtime:ro"
     - "log_data:/var/log/apache2/"
    ports:
     - "443:443"
     - "80:80"
    networks:
     - scot-docker-net
    container_name: apache  
    image: sandialabs/scot_apache
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3

  activemq:
    volumes:
     - "/var/log/activemq:/var/log/activemq/log/"
    networks:
     - scot-docker-net
    container_name: activemq
    image: sandialabs/scot_activemq
  
  mongodb:
 
    volumes:
     - "/etc/timezone:/etc/timezone:ro"
     - "/etc/localtime:/etc/localtime:ro"
     - "mongodb_data:/var/lib/mongodb/"
     - "scot_backup_data:/opt/scotbackup/mongo/scot-prod/"
     - "log_data:/var/log/mongodb/"
    networks:
     - scot-docker-net
    container_name: mongodb
    image: sandialabs/scot_mongodb

  elastic:
   volumes:
     - "/etc/timezone:/etc/timezone:ro"
     - "/etc/localtime:/etc/localtime:ro"
     - "scot_backup:/opt/scotbackup/elastic/"
     - "elastic_data:/var/lib/elasticsearch/"
     - "log_data:/var/log/elasticsearch/"
   networks:
    - scot-docker-net
   container_name: elastic
   image: sandialabs/scot_elastic
 
  scot:
   volumes:
     - "log_data:/var/log/scot/"
     - "/etc/timezone:/etc/timezone:ro"
     - "/etc/localtime:/etc/localtime:ro"
     - "scot_files_data:/opt/scotfiles/"
     - "./public/:/opt/scot/public/"
     - "elastic_data:/var/lib/elasticsearch/"
     - "mongodb_data:/var/lib/mongodb/"
     - "scot_backup_data:/opt/scotbackup/"
     - "cached_images_data:/opt/scot/public/cached_images/"
   depends_on:
     - mongodb
     - activemq
   networks:
     - scot-docker-net
   container_name: scot
   image: sandialabs/scot_scot
  
  perl:
   image: sandialabs/scot_perl 
  
  flair: 
   volumes:
    - "log_data:/var/log/scot/"
    - "/etc/localtime:/etc/localtime:ro"
   depends_on:
    - mongodb
    - activemq
    - scot
   networks:
     - scot-docker-net
   container_name: flair
   image: sandialabs/scot_flair
  
  reflair:
   volumes:
    - "log_data:/var/log/scot/"
    - "/etc/localtime:/etc/localtime:ro"
   depends_on:
    - mongodb
    - activemq
    - scot
   networks:
     - scot-docker-net
   container_name: reflair
   image: sandialabs/scot_reflair

  stretch:
   image: scot_stretch
   volumes:
    - "log_data:/var/log/scot/"
    - "/etc/localtime:/etc/localtime:ro"
   depends_on:
    - mongodb
    - activemq
    - scot
   networks:
    - scot-docker-net
   container_name: stretch
   image: sandialabs/scot_stretch

  game:
   volumes:
    - "log_data:/var/log/scot/"
    - "/etc/localtime:/etc/localtime:ro"
   depends_on:
    - mongodb
    - scot
   networks:
     - scot-docker-net
   container_name: game
   image: sandialabs/scot_game
 #mail: 
 #  build:
 #    dockerfile: Dockerfile-Mail
 #    context: ./
 #  volumes: 
 #    - "/var/log/scot:/var/log/scot/"
 #  depends_on:
 #   - mongodb
 #   - scot
 #  container_name: mail
 #  image: sandialabs/scot-stretch

volumes:
  elastic_data: 
  log_data:
  mongodb_data:
  scot_files_data:
  scot_backup_data:
  cached_images_data:

networks:
  scot-docker-net:
    driver: bridge
