version: '3.4'
services:
  apache:
    build:
      dockerfile: Dockerfile-Apache
      context: ./
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
    volumes:
     - "~/log/apache2:/var/log/apache2/"
    ports:
     - "443:443"
     - "80:80"
    networks:
     - scot-docker-net
    container_name: apache  
    image: sandialabs/scot_apache
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3

  activemq:
    volumes:
     - "~/log/activemq:/var/log/activemq/log/"
    build:
      dockerfile: Dockerfile-Activemq
      context: ./ 
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
    networks:
     - scot-docker-net
    container_name: activemq
    image: sandialabs/scot_activemq
  
  mongodb:
    build:
      dockerfile: Dockerfile-Mongodb
      context: ./
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
    volumes:
     - "~/data/mongodb:/var/lib/mongodb/"
     - "~/scotbackup/mongo/scot-prod:/opt/scotbackup/mongo/scot-prod/:z"
     - "~/log:/var/log/"
    networks:
     - scot-docker-net
    container_name: mongodb
    depends_on: 
     - perl
    image: sandialabs/scot_mongodb

  elastic:
   build:
     dockerfile: Dockerfile-Elastic
     context: ./
     args: 
       http_proxy: ${http_proxy}
       https_proxy: ${https_proxy}
       HTTP_PROXY: ${HTTP_PROXY}
       HTTPS_PROXY: ${HTTPS_PROXY}
   volumes:
     - "~/scotbackup/elastic:/opt/scotbackup/elastic/:z"
     - "~/data/elasticsearch:/var/lib/elasticsearch/"
     - "~/log/elasticsearch:/var/log/elasticsearch/"
   networks:
    - scot-docker-net
   container_name: elastic
   image: sandialabs/scot_elastic
 
  scot:
    build:
      dockerfile: Dockerfile-Scot
      context: ./
    volumes:
     - "~/log/scot:/var/log/scot/"
     - "~/scotfiles:/opt/scotfiles/"
     - "./public/:/opt/scot/public/"
     - "./pubdev/:/opt/scot/pubdev"
     - "~/data/elasticsearch:/var/lib/elasticsearch/"
     - "~/data/mongodb:/var/lib/mongodb/"
     - "~/scotbackup:/opt/scotbackup/:z"
     - "~/cached_images:/opt/scot/public/cached_images/"
    depends_on:
     - perl
     - mongodb
     - activemq
    networks:
     - scot-docker-net
    container_name: scot
    image: sandialabs/scot_scot
  
  perl:
    build: 
      dockerfile: Dockerfile-Perl
      context: ./
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
    image: sandialabs/scot_perl 
  
  flair:
   build:
     dockerfile: Dockerfile-Flair
     context: ./
   volumes:
    - "~/log/scot:/var/log/scot/"
   depends_on:
    - mongodb
    - activemq
    - scot
   networks:
     - scot-docker-net
   container_name: flair
   image: sandialabs/scot_flair
  
  reflair:
   build:
     dockerfile: Dockerfile-Reflair
     context: ./
   volumes:
    - "~/log/scot:/var/log/scot/"
    
   depends_on:
    - mongodb
    - activemq
    - scot
   networks:
     - scot-docker-net
   container_name: reflair
   image: sandialabs/scot_reflair

  stretch:
   build:
     dockerfile: Dockerfile-Stretch
     context: ./
   image: scot_stretch
   volumes:
    - "~/log/scot:/var/log/scot/"
   depends_on:
    - mongodb
    - activemq
    - scot
   networks:
    - scot-docker-net
   container_name: stretch
   image: sandialabs/scot_stretch

  game:
   build:
     dockerfile: Dockerfile-Game
     context: ./
   volumes:
    - "~/log/scot:/var/log/scot/"
    
   depends_on:
    - mongodb
    - scot
   networks:
     - scot-docker-net
   container_name: game
   image: sandialabs/scot_game
  
  #mail: 
  # build:
  #   dockerfile: Dockerfile-Mail
  #   context: ./
  # volumes: 
  #   - "/var/log/scot:/var/log/scot/"
  # depends_on:
  #  - mongodb
  #  - scot
  # networks:
  #  - scot-docker-net
  # image: sandialabs/scot_mail
  # container_name: mail

networks:
  scot-docker-net:
    driver: bridge
